# Generated by Django 5.1.1 on 2024-10-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediJeevan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
